# Generated by Django 5.1.7 on 2025-03-31 23:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('SchedulerApp', '0005_timetable'),
    ]

    operations = [
        migrations.AlterField(
            model_name='meetingtime',
            name='time',
            field=models.CharField(choices=[('9:00 - 11:00', '9:00 - 11:00'), ('11:00 - 1:00', '11:00 - 1:00'), ('2:00 - 4:00', '2:00 - 4:00'), ('4:00 - 6:00', '4:00 - 6:00')], default='11:30 - 12:30', max_length=50),
        ),
    ]
